from enum import Enum

class PrimitiveVocabulary(Enum):
    BIN = "bin"
    CAST = "cast"
    CONVERT_DATE = "convert_date"
    CONVERT_UNITS = "convert_units"
    DO_NOTHING = "do_nothing"
    ENUM_TO_ENUM = "enum_to_enum"
    EXTRACT_REGEX = "extract_regex"
    FORMAT_NUMBER = "format_number"
    MAP_EACH = "map_each"
    MISSING_CODE = "missing_code"
    NORMALIZE_BOOLEAN = "normalize_boolean"
    NORMALIZE_TEXT = "normalize_text"
    OFFSET = "offset"
    PARSE_ARRAY = "parse_array"
    REDUCE = "reduce"
    ROUND = "round"
    SCALE = "scale"
    SUBSTITUTE = "substitute"
    THRESHOLD = "threshold"
    TRUNCATE = "truncate"
    VALIDATE_PATTERN = "validate_pattern"
